# Header

menu:
  主页: /
  # 标签: /tags
  归档: /archives
  # 分类: /categories

# SubNav
subnav:
  github: "https://github.com/Jafeney"
  # weibo: "#"
  # rss: "#"
  segmentfault: "https://segmentfault.com/u/jafeney"
  zhihu: "https://www.zhihu.com/people/jafeney-lou/activities"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:692270687@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '海内存知己，天涯若比邻'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: "http://photo.jafeney.com:9999/file/Tt5HgGiKKsq1A7oSGnqq7FQG.png"
# 微信二维码图片地址
weixin: "http://photo.jafeney.com:9999/file/K0VhpLd4WrFL7ynleExrdZLL.png"

# Miscellaneous
baidu_analytics: '4c0fe03f16c08a15b32cda310c30b262'
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "http://avatar.csdn.net/F/8/E/1_u011413061.jpg"

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
# 热评论
duoshuo_hotartical: true
# 多说账号
duoshuo_shortname: jafeney


# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  强的bysocket: http://www.bysocket.com
  豪的Rapharino: http://rapharino.com
  黄的leo: http://www.e2718281828459.com
  我的csdn: http://blog.csdn.net/u011413061
  我的图片: http://photo.jafeney.com
  我的Royal: http://royal.jafeney.com

aboutme: Jafeney Lou，一个安静的代码客
